controller_joint_names: ['', 'FM_joint', 'FLA_joint', 'FLH_joint', 'FLK_joint', 'FRA_joint', 'FRH_joint', 'FRK_joint', 'BM_joint', 'BLA_joint', 'BLH_joint', 'BLK_joint', 'BRA_joint', 'BRH_joint', 'BRK_joint', ]
